# Generated by Django 4.2.16 on 2024-10-22 15:01

import chess
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_app", "0002_alter_challenge_unique_together_game_move_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chessgame",
            name="fen",
            field=models.TextField(default=chess.Board.fen),
        ),
    ]
