# Generated by Django 4.2.16 on 2024-12-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_app", "0003_alter_chessgame_fen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chessgame",
            name="fen",
            field=models.TextField(
                default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
            ),
        ),
    ]
