# Generated by Django 4.2.16 on 2024-12-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_app", "0005_onlineuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineuser",
            name="connection_count",
            field=models.IntegerField(default=0),
        ),
    ]
